# Generated by Django 3.0.4 on 2020-03-07 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroHabitacion', models.CharField(max_length=3)),
                ('huespedes', models.IntegerField()),
                ('precio', models.IntegerField()),
                ('reservada', models.BooleanField()),
                ('ocupada', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localizador', models.CharField(max_length=10)),
                ('idCliente', models.IntegerField()),
                ('numeroHabitacion', models.CharField(max_length=3)),
                ('fechaIn', models.DateField()),
                ('fechaOut', models.DateField()),
                ('numHuespedes', models.IntegerField()),
                ('precio', models.IntegerField()),
            ],
        ),
    ]
