# Generated by Django 3.0.4 on 2020-03-08 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prueba',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localizador', models.CharField(max_length=10)),
                ('idCliente', models.IntegerField()),
                ('fechaOut', models.DateField()),
            ],
        ),
    ]
