# Generated by Django 3.0.4 on 2020-03-08 15:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_prueba'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prueba',
        ),
        migrations.AddField(
            model_name='habitacion',
            name='fechaIn',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='habitacion',
            name='fechaOut',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='apellidosCliente',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='nombreCliente',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
